/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Common stuff not belonging to a certain abstraction level.
 */
module com.example.tracker.common {
  exports com.example.tracker.common;

  requires transitive org.tentackle.pdo;

  provides org.tentackle.common.ModuleHook with com.example.tracker.common.service.Hook;
}
