/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.rmi;

/**
 * Marker interface for remote delegates that should be transmitted in a secure way.<br>
 * RMI traffic of such delegates will be encrypted via SSL, if the server is configured properly.
 */
public interface RemoteSecurable {
}