/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.rmi;

import org.tentackle.dbms.rmi.RemoteDbSession;

/**
 * Interface for the remote session.
 */
public interface TrackerRemoteDbSession extends RemoteDbSession {

}