/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.rmi;

import org.tentackle.dbms.rmi.RemoteDbConnection;

/**
 * Interface for the appliction specific connection.
 */
public interface TrackerConnection extends RemoteDbConnection {

}
