/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui.theme;

import com.example.tracker.gui.GuiBundle;

import org.tentackle.app.Application;
import org.tentackle.bind.Bindable;
import org.tentackle.fx.AbstractFxController;
import org.tentackle.fx.Fx;
import org.tentackle.fx.FxControllerService;
import org.tentackle.fx.ThemeUtilities;
import org.tentackle.fx.component.FxButton;
import org.tentackle.fx.component.FxChoiceBox;

import javafx.application.ColorScheme;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.stage.Modality;
import javafx.stage.Stage;
import java.util.ResourceBundle;

/**
 * Controller for changing the user's theme.
 *
 * @author harald
 */
@FxControllerService
public class ChangeThemeView extends AbstractFxController {

  /**
   * Shows the dialog and prompts the user to change the theme.
   *
   * @param owner the owner view or window of the dialog
   */
  public static void showDialog(Object owner) {
    ChangeThemeView controller = Fx.load(ChangeThemeView.class);
    Stage stage = Fx.createStage(Modality.APPLICATION_MODAL, owner);
    Scene scene = Fx.createScene(controller.getView());
    stage.setScene(scene);
    stage.setTitle(GuiBundle.getString("change theme"));
    Fx.show(stage);
  }


  @Bindable
  private String mode;
  private String automaticMode;
  private String darkMode;
  private String lightMode;

  @Bindable
  private String theme;

  @FXML
  private FxChoiceBox<String> modeField;
  @FXML
  private FxChoiceBox<String> themeField;
  @FXML
  private FxButton saveButton;
  @FXML
  private FxButton cancelButton;

  @FXML
  private ResourceBundle resources;

  @FXML
  private void initialize() {
    modeField.setDeselectAllowed(false);
    themeField.setDeselectAllowed(false);
    saveButton.setGraphic(Fx.createGraphic("save"));
    saveButton.setOnAction(_ -> save());

    cancelButton.setGraphic(Fx.createGraphic("close"));
    cancelButton.setOnAction(_ -> close());
  }

  @Override
  public void configure() {
    automaticMode = resources.getString("automatic");
    darkMode = resources.getString("dark");
    lightMode = resources.getString("light");
    ThemeUtilities.ThemePreferences themePreferences = ThemeUtilities.getInstance().loadPreferences(Application.getInstance().getClass());
    if (themePreferences.darkMode() != null) {
      mode = themePreferences.darkMode() ? darkMode : lightMode;
    }
    else {
      mode = automaticMode;
    }
    modeField.getItems().add(automaticMode);
    modeField.getItems().add(lightMode);
    modeField.getItems().add(darkMode);

    theme = ThemeUtilities.getInstance().getThemeName();
    themeField.getItems().addAll(ThemeUtilities.getInstance().getSupportedThemes());
    getContainer().updateView();
  }

  private void save() {
    Boolean modeValue = null;
    if (darkMode.equals(mode)) {
      modeValue = true;
    }
    else if (lightMode.equals(mode)) {
      modeValue = false;
    }
    ThemeUtilities.ThemePreferences themePreferences = new ThemeUtilities.ThemePreferences(modeValue, theme);
    ThemeUtilities.getInstance().savePreferences(Application.getInstance().getClass(), themePreferences);
    if (themePreferences.darkMode() == null) {
      themePreferences = themePreferences.withDarkMode(Platform.getPreferences().getColorScheme() == ColorScheme.DARK);
    }
    ThemeUtilities.getInstance().applyThemePreferences(themePreferences);
    close();
  }

  private void close() {
    getStage().close();
  }

}
