/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui;

/**
 * GUI constants.
 */
public class GuiConstants {

  /**
   * The application specific menu items group.
   */
  public static final String ITEM_GROUP = "Tracker";

  private GuiConstants() {}
}
