/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui;

import org.tentackle.fx.DefaultImageProvider;
import org.tentackle.fx.ImageProviderService;

/**
 * Application specific image provider.
 */
@ImageProviderService(TrackerImageProvider.REALM)
public class TrackerImageProvider extends DefaultImageProvider {

  /**
   * The application's image realm.
   */
  public static final String REALM = "Tracker";

}
