/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui;

import org.tentackle.fx.IkonliGraphicProvider;
import org.tentackle.fx.GraphicProviderService;

import java.util.HashMap;
import java.util.Map;

/**
 * Application specific icon provider.
 */
@GraphicProviderService(TrackerGraphicProvider.REALM)
public class TrackerGraphicProvider extends IkonliGraphicProvider {

  /**
   * The application's realm.
   */
  public static final String REALM = "Tracker";



  @Override
  protected String translateName(String name) {
    String transName = getNameMap().get(name);
    return transName != null ? transName : name;
  }


  private Map<String, String> nameMap;

  private Map<String, String> getNameMap() {
    if (nameMap == null) {
      Map<String, String> nm = new HashMap<>();

      nm.put("message", "mdi2m-message-outline");
      nm.put("user", "mdi2a-account");
      nm.put("usergroup", "mdi2a-account-multiple");

      nameMap = nm;
    }
    return nameMap;
  }

}
