/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server.auth;

import com.example.tracker.pdo.md.User;

import org.tentackle.common.Service;
import org.tentackle.log.Logger;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.Pdo;
import org.tentackle.session.Session;
import org.tentackle.session.auth.Authentication;
import org.tentackle.session.auth.AuthenticationException;
import org.tentackle.session.auth.AuthenticationProvider;
import org.tentackle.session.auth.Credentials;
import org.tentackle.session.auth.DefaultAuthentication;
import org.tentackle.session.auth.PasswordCredentials;

import java.util.Objects;

/**
 * Authenticates a user by its password.
 * <p>
 * This is the application's username/password login: look up the user, compare the hashed password
 * and check that the user is allowed to log in at all.
 * <p>
 * To add single sign-on, write another {@code @Service(AuthenticationProvider.class)} that verifies
 * a token and leaves the user id at zero, plus a {@code @Service(UserResolver.class)} mapping the
 * token's subject onto a {@link User}. Both mechanisms then coexist, which is what service accounts
 * usually need.
 */
@Service(AuthenticationProvider.class)
public class TrackerPasswordAuthenticationProvider implements AuthenticationProvider {

  private static final Logger LOGGER = Logger.get();


  /**
   * Creates the provider.
   */
  public TrackerPasswordAuthenticationProvider() {
    // services need a public no-arg constructor
  }


  @Override
  public boolean supports(Credentials credentials) {
    return credentials instanceof PasswordCredentials;
  }

  @Override
  public Authentication authenticate(Credentials credentials) {
    PasswordCredentials passwordCredentials = (PasswordCredentials) credentials;
    String username = passwordCredentials.getUserName();
    DomainContext context = Pdo.createDomainContext(Session.getSession());
    User user = Pdo.create(User.class, context).selectByUniqueDomainKey(username);
    if (user == null) {
      // don't log the username, since it could be the password (mixed up by the user accidentally)
      LOGGER.warning("attempt to login for unknown user");
    }
    else {
      if (Objects.equals(user.hash(passwordCredentials.getPassword()), user.selectPasswordHash())) {
        if (!user.isLoginAllowed()) {
          LOGGER.warning("attempt to login for disabled user {0} (matching password)", username);
          user = null;
        }
      }
      else {
        LOGGER.warning("attempt to login with wrong password for user {0}", username);
        user = null;
      }
    }

    if (user == null) {
      throw new AuthenticationException("login refused");
    }

    // we know the user already, so there is nothing left for a UserResolver to do
    Authentication authentication = new DefaultAuthentication(username, credentials);
    authentication.setUserId(user.getId());
    authentication.setUserClassId(user.getClassId());
    return authentication;
  }

}
