/*
 * Generated by operation wizard from template ${.current_template_name}.
 */

package ${domainPackage};

import ${operationPackage}.${operationInterface};
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.DomainOperation;

/**
 * Domain interface for {@link ${operationInterface}}.
 */
<#if abstractOperation == "true">
public interface ${domainInterface}<T extends ${operationInterface}<T>>
       extends ${superDomainInterface}<T> {
<#else>
public interface ${domainInterface}
       extends ${superDomainInterface}<${operationInterface}> {
</#if>

}
