/*
 * Generated by wurbelizer from template ${.current_template_name}.
 */

package ${remoteImplPackage};

import ${operationPackage}.${operationInterface};
<#if persistenceImplPackage != remoteImplPackage>
import ${persistenceImplPackage}.${persistenceImplementation};
</#if>
<#if remotePackage != remoteImplPackage>
import ${remotePackage}.${remoteInterface};
</#if>
<#if superImplPackage != remoteImplPackage>
import ${superImplPackage}.${superImplementation};
</#if>

import java.rmi.RemoteException;
import java.util.List;
import org.tentackle.common.BMoney;
import org.tentackle.common.Binary;
import org.tentackle.common.DMoney;
import org.tentackle.common.Date;
import org.tentackle.common.Time;
import org.tentackle.common.Timestamp;
import org.tentackle.dbms.rmi.RemoteDbSessionImpl;
import org.tentackle.misc.TrackedList;
import org.tentackle.pdo.DomainContext;

/**
 * Remote delegate implementation for {@link ${persistenceImplementation}}.
 */
<#if abstractOperation == "true">
public class ${remoteImplementation}<T extends ${operationInterface}<T>, P extends ${persistenceImplementation}<T, P>>
       extends ${superImplementation}<T, P>
       implements ${remoteInterface}<T, P> {

  /**
   * Creates the remote delegate for {@link ${persistenceImplementation}}.
   *
   * @param serverSession the RMI session
   * @param persistenceClass the persistence implementation class
   * @param operationClass the operation interface class
   */
  public ${remoteImplementation}(RemoteDbSessionImpl serverSession, Class<P> persistenceClass, Class<T> operationClass) {
    super(serverSession, persistenceClass, operationClass);
  }
<#else>
public class ${remoteImplementation}
       extends ${superImplementation}<${operationInterface}, ${persistenceImplementation}>
       implements ${remoteInterface} {

  /**
   * Creates the remote delegate for {@link ${persistenceImplementation}}.
   *
   * @param serverSession the RMI session
   * @param persistenceClass the persistence implementation class
   * @param operationClass the operation interface class
   */
  public ${remoteImplementation}(RemoteDbSessionImpl serverSession, Class<${persistenceImplementation}> persistenceClass, Class<${operationInterface}> operationClass) {
    super(serverSession, persistenceClass, operationClass);
  }
</#if>

  // @wurblet inclrmi Include --missingok .$classname/methods

}
