/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Desktop FX client module.
 */
module com.example.tracker.client {
  exports com.example.tracker.client;

  requires com.example.tracker.gui;
  requires com.example.tracker.persist;
  requires com.example.tracker.domain;

  requires org.tentackle.fx.rdc;
  requires org.tentackle.fx.rdc.update;

  requires javafx.graphics;
  requires java.rmi;

  provides org.tentackle.common.ModuleHook with com.example.tracker.client.service.Hook;

  // SLF4J isnt a module yet. For some odd reason, we need a lookup scan for deps on the classpath.
  // Otherwise non-modularized deps cannot be located via META-INF/services.
  uses org.tentackle.log.Logger;
}
