/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.security;

import org.tentackle.common.Service;
import org.tentackle.security.DefaultSecurityFactory;
import org.tentackle.security.SecurityFactory;
import org.tentackle.security.SecurityManager;

/**
 * Application specific security factory.
 */
@Service(SecurityFactory.class)
public class TrackerSecurityFactory extends DefaultSecurityFactory {

  @Override
  protected SecurityManager createSecurityManager() {
    return new TrackerSecurityManager();
  }

}