/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.domain;

import com.example.tracker.pdo.md.OrgUnit;

import org.tentackle.pdo.DomainObject;

/**
 * Domain interface for OrgUnit.
 *
 * @param <T> the OrgUnit type
 */
public interface OrgUnitDomain<T extends OrgUnit<T>> extends DomainObject<T> {

}
