/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.domain;

import com.example.tracker.pdo.md.User2Group;

import org.tentackle.pdo.DomainObject;

/**
 * Domain interface for User2Group.
 */
public interface User2GroupDomain extends DomainObject<User2Group> {

}
