/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.domain;

import com.example.tracker.pdo.md.User;

/**
 * Domain interface for User.
 */
public interface UserDomain extends OrgUnitDomain<User> {

}
