/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.domain;

import com.example.tracker.pdo.md.UserGroup;

/**
 * Domain interface for UserGroup.
 */
public interface UserGroupDomain extends OrgUnitDomain<UserGroup> {

}
