/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Domain logic implementation module.
 */
module com.example.tracker.domain {
  exports com.example.tracker.domain;
  exports com.example.tracker.domain.md;
  exports com.example.tracker.domain.td;

  requires transitive com.example.tracker.pdo;

  requires transitive org.tentackle.domain;

  provides org.tentackle.common.ModuleHook with com.example.tracker.domain.service.Hook;
}
