/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.common;

/**
 * Application specific constants.
 */
public class Constants {

  /**
   * Number pool realm of Tracker.
   */
  public static final String POOL_REALM = "Tracker";

  private Constants() {}
}
