/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.common;

import org.tentackle.common.Service;
import org.tentackle.pdo.DefaultDomainContextFactory;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.DomainContextFactory;
import org.tentackle.session.Session;

/**
 * Application specific domain context factory.
 */
@Service(DomainContextFactory.class)
public class TrackerDomainContextFactory extends DefaultDomainContextFactory {

  @Override
  public DomainContext create(Session session) {
    return new TrackerDomainContext(session);
  }

  @Override
  public DomainContext create(Session session, boolean sessionImmutable) {
    return new TrackerDomainContext(session, sessionImmutable);
  }

}
