/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * FX GUI module.
 */
open module com.example.tracker.gui {
  exports com.example.tracker.gui;
  exports com.example.tracker.gui.main;

  requires transitive com.example.tracker.pdo;
  requires transitive org.tentackle.fx.rdc;

  provides org.tentackle.common.ModuleHook with com.example.tracker.gui.service.Hook;
}
