/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Middle tier server module.
 */
module com.example.tracker.server {
  exports com.example.tracker.server;
  exports com.example.tracker.server.rmi;

  requires transitive com.example.tracker.persist;
  requires com.example.tracker.domain;
  requires transitive org.tentackle.update;

  provides org.tentackle.common.ModuleHook with com.example.tracker.server.service.Hook;
}