/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.domain.md;

import com.example.tracker.pdo.md.User;
import com.example.tracker.pdo.md.domain.UserDomain;

import org.tentackle.common.StringHelper;
import org.tentackle.pdo.DomainObjectService;

import java.io.Serial;

/**
 * Domain implementation for User.
 */
@DomainObjectService(User.class)
public class UserDomainImpl extends OrgUnitDomainImpl<User, UserDomainImpl> implements UserDomain {

  @Serial
  private static final long serialVersionUID = 1L;

  private static final char[] SALT = {'E', 'X', 'A', 'M', 'P', 'L', 'E'};

  //<editor-fold defaultstate="collapsed" desc="constructors">

  /**
   * Creates a domain object for a PDO.
   *
   * @param pdo the persistent domain object
   */
  public UserDomainImpl(User pdo) {
    super(pdo);
  }

  /**
   * Creates a domain object.
   */
  public UserDomainImpl() {
    super();
  }

  //</editor-fold>

  // @wurblet domainMethods DomainMethods

//<editor-fold defaultstate="collapsed" desc="code 'domainMethods' generated by wurblet DomainMethods">//GEN-BEGIN:domainMethods


//</editor-fold>//GEN-END:domainMethods

  @Override
  public String hash(char[] password) {
    if (password != null && password.length == 0) {
      password = null;
    }
    return StringHelper.hash("SHA-256", SALT, password);
  }

}
