/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui.main;

import com.example.tracker.common.TrackerDomainContext;
import com.example.tracker.gui.TrackerGraphicProvider;
import com.example.tracker.gui.about.AboutView;
import com.example.tracker.gui.password.ChangePasswordView;
import com.example.tracker.gui.theme.ChangeThemeView;
import com.example.tracker.gui.prefs.PreferencesDialog;
import com.example.tracker.pdo.md.User;
import com.example.tracker.pdo.md.UserGroup;
import com.example.tracker.pdo.td.Message;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.stage.Modality;
import javafx.stage.Stage;

import org.tentackle.app.Application;
import org.tentackle.common.StringHelper;
import org.tentackle.fx.AbstractFxController;
import org.tentackle.fx.Fx;
import org.tentackle.fx.FxControllerService;
import org.tentackle.fx.FxRuntimeException;
import org.tentackle.fx.FxUtilities;
import org.tentackle.fx.MacUtilities;
import org.tentackle.fx.ThemeUtilities;
import org.tentackle.fx.component.FxButton;
import org.tentackle.fx.rdc.Rdc;
import org.tentackle.fx.rdc.admin.SessionsView;
import org.tentackle.fx.rdc.security.SecurityDialogFactory;
import org.tentackle.pdo.AdminExtension;
import org.tentackle.pdo.DomainContextProvider;
import org.tentackle.pdo.PdoUtilities;
import org.tentackle.pdo.PersistentDomainObject;
import org.tentackle.security.SecurityFactory;
import org.tentackle.security.pdo.Security;

import java.io.IOException;
import java.io.InputStream;
import java.util.ResourceBundle;

/**
 * FX main controller.
 */
@FxControllerService
public class MainController extends AbstractFxController implements DomainContextProvider {

  @FXML
  private BorderPane borderPane;

  @FXML
  private MenuBar menuBar;

  @FXML
  private MenuItem securityManagerItem;

  @FXML
  private MenuItem sessionsItem;

  @FXML
  private MenuItem preferencesItem;

  @FXML
  private MenuItem themeItem;

  @FXML
  private MenuItem passwordItem;

  @FXML
  private MenuItem exitItem;

  @FXML
  private MenuItem editUserItem;

  @FXML
  private MenuItem editUserGroupItem;

  @FXML
  private MenuItem searchUserItem;

  @FXML
  private MenuItem searchUserGroupItem;

  @FXML
  private MenuItem searchMessageItem;

  @FXML
  private MenuItem helpItem;

  @FXML
  private MenuItem aboutItem;

  @FXML
  private ResourceBundle resources;


  @Override
  public TrackerDomainContext getDomainContext() {
    return (TrackerDomainContext) Application.getInstance().getDomainContext();
  }

  @FXML
  public void initialize() {

    loadCenterImage();
    ThemeUtilities.getInstance().darkModeProperty().subscribe(this::loadCenterImage);

    securityManagerItem.setGraphic(Fx.createGraphic("security"));
    securityManagerItem.setOnAction(_ ->
            SecurityDialogFactory.getInstance().showDialog(getView(), on(Security.class).getClassId(), getDomainContext()));

    sessionsItem.setGraphic(Fx.createGraphic("session"));
    sessionsItem.setOnAction(_ -> manageSessions());

    preferencesItem.setGraphic(Fx.createGraphic("preferences"));
    preferencesItem.setOnAction(_ -> PreferencesDialog.show(getView()));

    themeItem.setGraphic(Fx.createGraphic("theme"));
    themeItem.setOnAction(e -> ChangeThemeView.showDialog(Fx.getStage(getView())));

    passwordItem.setGraphic(Fx.createGraphic("password"));
    passwordItem.setOnAction(_ -> ChangePasswordView.showDialog(getView(), PdoUtilities.getInstance().getUser(getDomainContext()), false));

    exitItem.setGraphic(Fx.createGraphic("exit"));
    exitItem.setOnAction(_ -> exit());

    editUserItem.setGraphic(Fx.createGraphic(TrackerGraphicProvider.REALM, "user"));
    editUserItem.setOnAction(_ -> edit(User.class));

    editUserGroupItem.setGraphic(Fx.createGraphic(TrackerGraphicProvider.REALM, "usergroup"));
    editUserGroupItem.setOnAction(_ -> edit(UserGroup.class));

    searchUserItem.setGraphic(Fx.createGraphic(TrackerGraphicProvider.REALM, "user"));
    searchUserItem.setOnAction(_ -> search(User.class));

    searchUserGroupItem.setGraphic(Fx.createGraphic(TrackerGraphicProvider.REALM, "usergroup"));
    searchUserGroupItem.setOnAction(_ -> search(UserGroup.class));

    searchMessageItem.setGraphic(Fx.createGraphic(TrackerGraphicProvider.REALM, "message"));
    searchMessageItem.setOnAction(_ -> search(Message.class));

    helpItem.setGraphic(Fx.createGraphic("help"));
    helpItem.setOnAction(_ -> help());

    aboutItem.setGraphic(Fx.createGraphic("about"));
    aboutItem.setOnAction(_ -> AboutView.show(getView()));
  }

  @Override
  public void configure() {
    securityManagerItem.setDisable(!SecurityDialogFactory.getInstance().isDialogAllowed(getDomainContext()));
    sessionsItem.setDisable(!SecurityFactory.getInstance().getSecurityManager().evaluate(
      getDomainContext(), SecurityFactory.getInstance().getExecutePermission(), AdminExtension.class).isAccepted());
    preferencesItem.setDisable(!SecurityFactory.getInstance().getSecurityManager().evaluate(
      getDomainContext(), SecurityFactory.getInstance().getExecutePermission(), PreferencesDialog.class).isAccepted());

    if (StringHelper.getPlatform().contains("mac")) {
      MacUtilities.getInstance().toSystemMenuBar(menuBar);
    }
  }

  /**
   * Asks the user whether to exit the application and does so if yes.
   */
  public void exit() {
    Fx.yes(getView(), resources.getString("ExitAction"), false, Fx::terminate);
  }


  /**
   * Shows the edit dialog for given PDO-class.
   *
   * @param <T> the pdo type
   * @param clazz the pdo class
   */
  private <T extends PersistentDomainObject<T>> void edit(Class<T> clazz) {
    Rdc.displayCrudStage(on(clazz), true, Fx.getStage(getView()));
  }

  /**
   * Shows the search dialog for given PDO-class.
   *
   * @param <T> the pdo type
   * @param clazz the pdo class
   */
  private <T extends PersistentDomainObject<T>> void search(Class<T> clazz) {
    Rdc.displaySearchStage(on(clazz), Fx.getStage(getView()), false);
  }

  /**
   * Shows the help browser.
   */
  private void help() {
    FxUtilities.getInstance().showHelp(null);
  }

  /**
   * Manages server sessions.
   */
  private void manageSessions() {
    Stage stage = Fx.createStage(Modality.APPLICATION_MODAL, getView());
    SessionsView controller = Fx.load(SessionsView.class);
    FxButton closeButton = Fx.create(Button.class);
    closeButton.setText(resources.getString("close"));
    closeButton.setGraphic(Fx.createGraphic("close"));
    closeButton.setOnAction(e -> stage.close());
    controller.getButtonBox().getChildren().add(closeButton);
    Scene scene = Fx.createScene(controller.getView());
    stage.setScene(scene);
    stage.setTitle(resources.getString("Sessions"));
    Fx.show(stage);
  }

  private void loadCenterImage() {
    // just to show something nice (to be replaced by some application relevant stuff)
    try (InputStream is = getClass().getResourceAsStream(
      ThemeUtilities.getInstance().isDarkMode() ?
        "/com/example/tracker/gui/images/tentackle-dark.png" : "/com/example/tracker/gui/images/tentackle.png")) {
      borderPane.setCenter(new ImageView(new Image(is)));
    }
    catch (IOException iox) {
      throw new FxRuntimeException("loading center image failed", iox);
    }
  }

}
