/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server;

import org.testng.annotations.Test;

public class RunServer {

  @Test
  public void runServer() {
    run(new String[] {"--statistics"});
  }

  private synchronized void run(String[] args) {
    new TrackerServer().start(args);
    try {
      wait();   // keep it running...
    }
    catch (InterruptedException e) {}
  }

}