/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server;

/**
 * Test constants.
 */
public class TestConstants {

  /** test group to initialize the CI database. */
  public static final String GROUP_INITDB = "initdb";

}
