/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.client;

import org.testng.annotations.Test;

public class RunClient {

  @Test
  public void runClient() {
    run(new String[] {"--statistics"});
  }

  @Test
  public void runClientDE() {
    run(new String[] {"--statistics", "--locale=de_DE"});
  }

  private synchronized void run(String[] args) {
    new TrackerFxClient().start(args);
    try {
      wait();   // keep it running...
    }
    catch (InterruptedException e) {}
  }

}