/*
 * Generated by PDO wizard from template ${.current_template_name}.
 */

package ${domainPackage};

import ${pdoPackage}.${pdoInterface};
import org.tentackle.pdo.DomainObject;

/**
 * Domain interface for {@link ${pdoInterface}}.
 */
<#if pdoInheritance != "NONE" && pdoInheritance != "EMBEDDED">
public interface ${domainInterface}<T extends ${pdoInterface}<T>>
       extends ${superDomainInterface}<T> {
<#else>
public interface ${domainInterface}
       extends ${superDomainInterface}<${pdoInterface}> {
</#if>

}
