/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui;

import org.tentackle.fx.rdc.testng.ControllerTest;

/**
 * Tests all FX controllers.
 */
public class TestControllers extends ControllerTest {}
