/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui;

import org.tentackle.fx.rdc.testng.GuiProviderTest;

/**
 * Tests all GuiProviders.
 */
public class TestGuiProviders extends GuiProviderTest {}
