/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui;

import org.tentackle.fx.rdc.testng.TableConfigurationProviderTest;

/**
 * Tests all TableConfigurationProviders.
 */
public class TestTableConfigurationProviders extends TableConfigurationProviderTest {}
