/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.md.rmi;

import com.example.tracker.pdo.md.UserGroup;
import com.example.tracker.persist.md.UserGroupPersistenceImpl;

/**
 * Remote delegate for {@link UserGroupPersistenceImpl}.
 */
public interface UserGroupRemoteDelegate
       extends OrgUnitRemoteDelegate<UserGroup,UserGroupPersistenceImpl> {

  // @wurblet inclrmi Include --missingok .$classname/methods

//<editor-fold defaultstate="collapsed" desc="code 'inclrmi' generated by wurblet Include">//GEN-BEGIN:inclrmi


//</editor-fold>//GEN-END:inclrmi

}
