/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo;

import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.Test;

import java.util.MissingResourceException;

/**
 * Tests the translations for enums.<br>
 * Those are not covered by the tentackle-check:bundles mojo because the parameter
 * of getString is not a literal.
 */
public class EnumI18nTest {

  private static final Class<?>[] ENUMS = {
      MessageType.class
      // to be cont'd ...
  };

  @Test
  public void testEnums() {
    for (Class<?> clazz : ENUMS) {
      Reporter.log("testing enum " + clazz.getName() + "<br>", true);
      for (Object constant: clazz.getEnumConstants()) {
        try {
          Reporter.log(constant.toString() + "<br>");    // this will use the bundle
        }
        catch (MissingResourceException mx) {
          Assert.fail("missing resource for " + clazz.getName() + ": " + mx.getMessage());
        }
      }
    }
  }

}
