url=${dbUrl}?sslmode=disable
user=${dbUser}
password=~${encryptedPasswd}

service=${dbService}
updateService=${updateService}
updateURL=${updateURL}
timeout=30

^javax.net.ssl.keyStore=@{RUNTIMEDIR?.}/conf/keystore.jks
^javax.net.ssl.keyStorePassword=~${encryptedCertPasswd}
