url=${dbUrl}?sslmode=disable
user=${dbUser}
password=~${encryptedPasswd}

service=${dbService}
updateService=${updateService}
updateURL=${updateURL}
timeout=30

^tentackle.ssl.keyStore=@{RUNTIMEDIR?.}/conf/keystore.p12
^tentackle.ssl.keyStorePassword=~${encryptedCertPasswd}
