/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Persistence implementation module.
 */
module com.example.tracker.persist {
  exports com.example.tracker.persist;
  exports com.example.tracker.persist.md;
  exports com.example.tracker.persist.md.rmi;
  exports com.example.tracker.persist.rmi;
  exports com.example.tracker.persist.td;
  exports com.example.tracker.persist.td.rmi;

  requires transitive com.example.tracker.pdo;
  requires transitive org.tentackle.persistence;

  provides org.tentackle.common.ModuleHook with com.example.tracker.persist.service.Hook;
}
