/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.md.trip;

import com.example.tracker.pdo.MasterData;
import com.example.tracker.persist.md.AbstractPersistentMasterData;

import org.tentackle.persist.trip.AbstractPersistentObjectRemoteDelegate;

/**
 * Base interface for master data remote delegates.
 */
public interface AbstractPersistentMasterDataRemoteDelegate<T extends MasterData<T>,
                                                            P extends AbstractPersistentMasterData<T,P>>
       extends AbstractPersistentObjectRemoteDelegate<T,P> {

}
