/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.md.trip;

import com.example.tracker.pdo.md.OrgUnit;
import com.example.tracker.persist.md.OrgUnitPersistenceImpl;

import org.tentackle.pdo.DomainContext;

/**
 * Remote delegate for {@link OrgUnitPersistenceImpl}.
 *
 * @param <T> the pdo interface
 * @param <P> the persistence implementation
 */
public interface OrgUnitRemoteDelegate<T extends OrgUnit<T>, P extends OrgUnitPersistenceImpl<T,P>>
       extends AbstractPersistentMasterDataRemoteDelegate<T,P> {

  // @wurblet inclrmi Include --missingok .$classname/methods

  //<editor-fold defaultstate="collapsed" desc="code 'inclrmi' generated by wurblet Include">//GEN-BEGIN:inclrmi

  T selectByUniqueDomainKey(DomainContext context, String name);

  //</editor-fold>//GEN-END:inclrmi

}
