/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.md.trip;

import com.example.tracker.pdo.md.User;
import com.example.tracker.persist.md.UserPersistenceImpl;

import org.tentackle.dbms.trip.RemoteDbSessionImpl;

/**
 * Remote delegate implementation for {@link UserPersistenceImpl}.
 */
public class UserRemoteDelegateImpl
       extends OrgUnitRemoteDelegateImpl<User,UserPersistenceImpl>
       implements UserRemoteDelegate {

  /**
   * Creates the remote delegate for {@link UserPersistenceImpl}.
   *
   * @param session the TRIP session
   * @param persistenceClass the persistence implementation class
   * @param pdoClass the pdo interface class
   */
  public UserRemoteDelegateImpl(RemoteDbSessionImpl session, Class<UserPersistenceImpl> persistenceClass, Class<User> pdoClass) {
    super(session, persistenceClass, pdoClass);
  }

  // @wurblet inclrmi Include --missingok .$classname/methods

  //<editor-fold defaultstate="collapsed" desc="code 'inclrmi' generated by wurblet Include">//GEN-BEGIN:inclrmi


  @Override
  public String selectPasswordHash(User obj) {
    obj.setSession(getSession());
    return obj.selectPasswordHash();
  }

  @Override
  public void updatePasswordHash(String password, User obj) {
    obj.setSession(getSession());
    obj.updatePasswordHash(password);
  }

  //</editor-fold>//GEN-END:inclrmi

}
