/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.md.trip;

import com.example.tracker.pdo.md.User;
import com.example.tracker.persist.md.UserPersistenceImpl;

/**
 * Remote delegate for {@link UserPersistenceImpl}.
 */
public interface UserRemoteDelegate
       extends OrgUnitRemoteDelegate<User,UserPersistenceImpl> {


  // @wurblet inclrmi Include --missingok .$classname/methods

  //<editor-fold defaultstate="collapsed" desc="code 'inclrmi' generated by wurblet Include">//GEN-BEGIN:inclrmi

  String selectPasswordHash(User obj);
  void updatePasswordHash(String password, User obj);

  //</editor-fold>//GEN-END:inclrmi

}
