/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.persist;

import com.example.tracker.pdo.md.OrgUnit;

import org.tentackle.bind.Bindable;
import org.tentackle.misc.ShortLongText;
import org.tentackle.pdo.DomainKey;
import org.tentackle.pdo.PersistentObject;
import org.tentackle.session.Persistent;
import org.tentackle.validate.validator.NotNull;

/**
 * Persistence interface for OrgUnit.
 *
 * @param <T> the orgunit type
 */
public interface OrgUnitPersistence<T extends OrgUnit<T>> extends PersistentObject<T>, ShortLongText {

  // @wurblet attributeNames AttributeNames

  //<editor-fold defaultstate="collapsed" desc="code 'attributeNames' generated by wurblet AttributeNames">//GEN-BEGIN:attributeNames


  /** attribute name for database column 'name'. */
  String AN_NAME = "name";

  /** attribute name for database column 'ocomment'. */
  String AN_COMMENT = "comment";

  //</editor-fold>//GEN-END:attributeNames


  // @wurblet columnLengths ColumnLengths

  //<editor-fold defaultstate="collapsed" desc="code 'columnLengths' generated by wurblet ColumnLengths">//GEN-BEGIN:columnLengths


  /** maximum number of characters for 'name'. */
  int CL_NAME = 20;

  /** maximum number of characters for 'comment'. */
  int CL_COMMENT = 256;

  //</editor-fold>//GEN-END:columnLengths


  // @wurblet methods Methods

  //<editor-fold defaultstate="collapsed" desc="code 'methods' generated by wurblet Methods">//GEN-BEGIN:methods


  /**
   * Gets the attribute 'name'.
   *
   * @return the short name
   */
  @Persistent(ordinal=5, comment="the short name")
  @NotNull(message="{ @('please enter the name') }")
  @Bindable(options="UC,MAXCOLS=20", ordinal=5)
  @DomainKey
  String getName();

  /**
   * Sets the attribute 'name'.
   *
   * @param name the short name
   */
  @Bindable(ordinal=5)
  void setName(String name);

  /**
   * Gets the attribute 'comment'.
   *
   * @return the optional comment
   */
  @Persistent(ordinal=6, comment="the optional comment")
  @Bindable(options="MAXCOLS=256", ordinal=6)
  String getComment();

  /**
   * Sets the attribute 'comment'.
   *
   * @param comment the optional comment
   */
  @Bindable(ordinal=6)
  void setComment(String comment);

  /**
   * Selects the OrgUnit by its unique domain key.
   *
   * @param name short name
   * @return the OrgUnit, null if no such PDO
   */
  T selectByUniqueDomainKey(String name);

  //</editor-fold>//GEN-END:methods


  // @wurblet relations Relations

//<editor-fold defaultstate="collapsed" desc="code 'relations' generated by wurblet Relations">//GEN-BEGIN:relations


//</editor-fold>//GEN-END:relations

}
