/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.persist;

import com.example.tracker.pdo.md.User;
import com.example.tracker.pdo.md.User2Group;
import com.example.tracker.pdo.md.UserGroup;

import org.tentackle.bind.Bindable;
import org.tentackle.misc.TrackedList;
import org.tentackle.pdo.PersistentObject;
import org.tentackle.session.Persistent;

/**
 * Persistence interface for User2Group.
 */
public interface User2GroupPersistence extends PersistentObject<User2Group> {

  // @wurblet attributeNames AttributeNames

  //<editor-fold defaultstate="collapsed" desc="code 'attributeNames' generated by wurblet AttributeNames">//GEN-BEGIN:attributeNames


  /** relation name for 'User user via userId'. */
  String RN_USER = "user";

  /** relation name for 'UserGroup userGroup via userGroupId'. */
  String RN_USERGROUP = "userGroup";

  /** attribute name for database column 'group_id'. */
  String AN_USERGROUPID = "userGroupId";

  /** attribute name for database column 'user_id'. */
  String AN_USERID = "userId";

  //</editor-fold>//GEN-END:attributeNames


  // @wurblet columnLengths ColumnLengths

//<editor-fold defaultstate="collapsed" desc="code 'columnLengths' generated by wurblet ColumnLengths">//GEN-BEGIN:columnLengths


//</editor-fold>//GEN-END:columnLengths


  // @wurblet methods Methods

  //<editor-fold defaultstate="collapsed" desc="code 'methods' generated by wurblet Methods">//GEN-BEGIN:methods


  /**
   * Gets the attribute 'userGroupId'.
   *
   * @return the user group ID
   */
  @Persistent(ordinal=0, comment="the user group ID")
  @Bindable(options="AUTOSELECT", ordinal=0)
  long getUserGroupId();

  /**
   * Sets the attribute 'userGroupId'.
   *
   * @param userGroupId the user group ID
   */
  @Bindable(ordinal=0)
  void setUserGroupId(long userGroupId);

  /**
   * Gets the attribute 'userId'.
   *
   * @return the user ID
   */
  @Persistent(ordinal=1, comment="the user ID")
  @Bindable(options="AUTOSELECT", ordinal=1)
  long getUserId();

  /**
   * Sets the attribute 'userId'.
   *
   * @param userId the user ID
   */
  @Bindable(ordinal=1)
  void setUserId(long userId);

  //</editor-fold>//GEN-END:methods


  // @wurblet relations Relations

  //<editor-fold defaultstate="collapsed" desc="code 'relations' generated by wurblet Relations">//GEN-BEGIN:relations


  /**
   * Gets the User user via userId.
   *
   * @return the user
   */
  @Bindable
  @Persistent(ordinal=0, comment="the user", component=false, parent=true)
  User getUser();

  /**
   * Sets the User user via userId.
   *
   * @param user the user
   */
  @Bindable
  void setUser(User user);

  /**
   * Gets the UserGroup userGroup via userGroupId.
   *
   * @return the userGroup
   */
  @Bindable
  @Persistent(ordinal=1, comment="the userGroup", component=false, parent=true)
  UserGroup getUserGroup();

  /**
   * Sets the UserGroup userGroup via userGroupId.
   *
   * @param userGroup the userGroup
   */
  @Bindable
  void setUserGroup(UserGroup userGroup);

  /**
   * Selects the component list of User2Group nmLinks via User2Group#userId.
   *
   * @param userId the user ID
   * @return the nmLinks
   */
  TrackedList<User2Group> selectByUserId(long userId);

  /**
   * Selects the component list of User2Group nmLinks via User2Group#userGroupId.
   *
   * @param userGroupId the user group ID
   * @return the nmLinks
   */
  TrackedList<User2Group> selectByUserGroupId(long userGroupId);

  //</editor-fold>//GEN-END:relations

}
