/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.persist;

import com.example.tracker.pdo.md.User;
import com.example.tracker.pdo.md.User2Group;
import com.example.tracker.pdo.md.UserGroup;

import org.tentackle.bind.Bindable;
import org.tentackle.misc.TrackedList;
import org.tentackle.session.Persistent;

/**
 * Persistence interface for User.
 */
public interface UserPersistence extends OrgUnitPersistence<User> {

  // @wurblet attributeNames AttributeNames

  //<editor-fold defaultstate="collapsed" desc="code 'attributeNames' generated by wurblet AttributeNames">//GEN-BEGIN:attributeNames


  /** relation name for 'component list of User2Group nmLinks via User2Group#userId'. */
  String RN_NMLINKS = "nmLinks";

  /** attribute name for database column 'login_allowed'. */
  String AN_LOGINALLOWED = "loginAllowed";

  /** attribute name for database column 'passwd_chgbl'. */
  String AN_PASSWORDCHANGEABLE = "passwordChangeable";

  /** attribute name for database column 'prefs_chgbl'. */
  String AN_CHANGINGPREFERENCESALLOWED = "changingPreferencesAllowed";

  /** attribute name for database column 'prefs_system'. */
  String AN_SYSTEMPREFERENCESONLY = "systemPreferencesOnly";

  //</editor-fold>//GEN-END:attributeNames


  // @wurblet columnLengths ColumnLengths

  //<editor-fold defaultstate="collapsed" desc="code 'columnLengths' generated by wurblet ColumnLengths">//GEN-BEGIN:columnLengths


  /** maximum number of characters for 'password'. */
  int CL_PASSWORD = 64;

  //</editor-fold>//GEN-END:columnLengths


  // @wurblet methods Methods

  //<editor-fold defaultstate="collapsed" desc="code 'methods' generated by wurblet Methods">//GEN-BEGIN:methods


  /**
   * Gets the attribute 'loginAllowed'.
   *
   * @return true if login is allowed
   */
  @Persistent(ordinal=10, comment="true if login is allowed")
  @Bindable(ordinal=10)
  boolean isLoginAllowed();

  /**
   * Sets the attribute 'loginAllowed'.
   *
   * @param loginAllowed true if login is allowed
   */
  @Bindable(ordinal=10)
  void setLoginAllowed(boolean loginAllowed);

  /**
   * Gets the attribute 'passwordChangeable'.
   *
   * @return true if user is allowed to change its own password
   */
  @Persistent(ordinal=11, comment="true if user is allowed to change its own password")
  @Bindable(ordinal=11)
  boolean isPasswordChangeable();

  /**
   * Sets the attribute 'passwordChangeable'.
   *
   * @param passwordChangeable true if user is allowed to change its own password
   */
  @Bindable(ordinal=11)
  void setPasswordChangeable(boolean passwordChangeable);

  /**
   * Gets the attribute 'changingPreferencesAllowed'.
   *
   * @return true if user is allowed to maintain its own preferences
   */
  @Persistent(ordinal=12, comment="true if user is allowed to maintain its own preferences")
  @Bindable(ordinal=12)
  boolean isChangingPreferencesAllowed();

  /**
   * Sets the attribute 'changingPreferencesAllowed'.
   *
   * @param changingPreferencesAllowed true if user is allowed to maintain its own preferences
   */
  @Bindable(ordinal=12)
  void setChangingPreferencesAllowed(boolean changingPreferencesAllowed);

  /**
   * Gets the attribute 'systemPreferencesOnly'.
   *
   * @return true if user is restricted to system preferences only
   */
  @Persistent(ordinal=13, comment="true if user is restricted to system preferences only")
  @Bindable(ordinal=13)
  boolean isSystemPreferencesOnly();

  /**
   * Sets the attribute 'systemPreferencesOnly'.
   *
   * @param systemPreferencesOnly true if user is restricted to system preferences only
   */
  @Bindable(ordinal=13)
  void setSystemPreferencesOnly(boolean systemPreferencesOnly);

  //</editor-fold>//GEN-END:methods


  // @wurblet relations Relations

  //<editor-fold defaultstate="collapsed" desc="code 'relations' generated by wurblet Relations">//GEN-BEGIN:relations


  /**
   * Gets the component list of User2Group nmLinks via User2Group#userId.
   *
   * @return the nmLinks
   */
  @Bindable
  @Persistent(ordinal=0, comment="the nmLinks")
  TrackedList<User2Group> getNmLinks();

  /**
   * Gets list of UserGroup joined via component list of User2Group nmLinks via User2Group#userId.
   *
   * @return list of userGroup
   */
  @Bindable
  @Persistent(ordinal=0, comment="the userGroups", component=false)
  TrackedList<UserGroup> getUserGroups();

  /**
   * Returns whether NmLinks is loaded.
   *
   * @return true if getNmLinks() invoked at least once
   */
  @Bindable
  boolean isNmLinksLoaded();

  //</editor-fold>//GEN-END:relations


  /**
   * Selects the password from the database.
   *
   * @return the password hash
   */
  String selectPasswordHash();

  /**
   * Updates the password in the database.
   *
   * @param password the password hash, null to disable
   */
  void updatePasswordHash(String password);

}
