/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.pdo.md.persist;

import com.example.tracker.pdo.md.User;
import com.example.tracker.pdo.md.User2Group;
import com.example.tracker.pdo.md.UserGroup;

import org.tentackle.bind.Bindable;
import org.tentackle.misc.TrackedList;
import org.tentackle.session.Persistent;

/**
 * Persistence interface for UserGroup.
 */
public interface UserGroupPersistence extends OrgUnitPersistence<UserGroup> {

  // @wurblet attributeNames AttributeNames

  //<editor-fold defaultstate="collapsed" desc="code 'attributeNames' generated by wurblet AttributeNames">//GEN-BEGIN:attributeNames


  /** relation name for 'component list of User2Group nmLinks via User2Group#userGroupId'. */
  String RN_NMLINKS = "nmLinks";

  //</editor-fold>//GEN-END:attributeNames


  // @wurblet columnLengths ColumnLengths

//<editor-fold defaultstate="collapsed" desc="code 'columnLengths' generated by wurblet ColumnLengths">//GEN-BEGIN:columnLengths


//</editor-fold>//GEN-END:columnLengths


  // @wurblet methods Methods

//<editor-fold defaultstate="collapsed" desc="code 'methods' generated by wurblet Methods">//GEN-BEGIN:methods


//</editor-fold>//GEN-END:methods


  // @wurblet relations Relations

  //<editor-fold defaultstate="collapsed" desc="code 'relations' generated by wurblet Relations">//GEN-BEGIN:relations


  /**
   * Gets the component list of User2Group nmLinks via User2Group#userGroupId.
   *
   * @return the nmLinks
   */
  @Bindable
  @Persistent(ordinal=0, comment="the nmLinks")
  TrackedList<User2Group> getNmLinks();

  /**
   * Gets list of User joined via component list of User2Group nmLinks via User2Group#userGroupId.
   *
   * @return list of user
   */
  @Bindable
  @Persistent(ordinal=0, comment="the users", component=false)
  TrackedList<User> getUsers();

  /**
   * Returns whether NmLinks is loaded.
   *
   * @return true if getNmLinks() invoked at least once
   */
  @Bindable
  boolean isNmLinksLoaded();

  //</editor-fold>//GEN-END:relations

}
