/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Daemon client module.
 */
module com.example.tracker.daemon {
  exports com.example.tracker.daemon;

  requires com.example.tracker.persist;
  requires com.example.tracker.domain;

  requires java.rmi;

  provides org.tentackle.common.ModuleHook with com.example.tracker.daemon.service.Hook;
}
