/*
 * Tracker generated by tentackle-project-archetype.
 */

/**
 * Daemon client module.
 */
module com.example.tracker.daemon {
  exports com.example.tracker.daemon;

  requires com.example.tracker.persist;
  requires com.example.tracker.domain;

  requires java.rmi;

  provides org.tentackle.common.ModuleHook with com.example.tracker.daemon.service.Hook;

  // SLF4J isnt a module yet. For some odd reason, we need a lookup scan for deps on the classpath.
  // Otherwise non-modularized deps cannot be located via META-INF/services.
  uses org.tentackle.log.Logger;
}
