/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.gui.prefs;

import com.example.tracker.common.TrackerPreferences;

import org.tentackle.bind.Bindable;
import org.tentackle.fx.AbstractFxController;

/**
 * Base controller class for a preferences tab.
 */
public abstract class AbstractPreferencesTabController extends AbstractFxController {

  @Bindable
  public TrackerPreferences getPref() {
    return TrackerPreferences.getInstance();
  }

}
