/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server.trip;

import com.example.tracker.common.TrackerSessionInfo;
import com.example.tracker.pdo.MessageType;
import com.example.tracker.pdo.md.User;
import com.example.tracker.pdo.td.Message;
import com.example.tracker.persist.trip.TrackerRemoteDbSession;
import com.example.tracker.server.ServerBundle;

import org.tentackle.app.Application;
import org.tentackle.common.LocaleProvider;
import org.tentackle.dbms.Db;
import org.tentackle.dbms.trip.RemoteDbConnectionImpl;
import org.tentackle.dbms.trip.RemoteDbSessionImpl;
import org.tentackle.log.Logger;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.Pdo;
import org.tentackle.session.AlreadyLoggedInException;
import org.tentackle.session.ModificationTracker;
import org.tentackle.session.SessionInfo;

import java.text.MessageFormat;

/**
 * Application-specific remote session.
 */
public class TrackerRemoteDbSessionImpl extends RemoteDbSessionImpl implements TrackerRemoteDbSession {

  private static final Logger LOGGER = Logger.get();


  private boolean loggedIn;   // true if session successfully logged in

  /**
   * Creates a session on a given connection.
   *
   * @param con the connection
   * @param clientInfo the session info from the client
   * @param serverInfo the session info to establish the connection to the database server
   */
  public TrackerRemoteDbSessionImpl(RemoteDbConnectionImpl con, SessionInfo clientInfo, SessionInfo serverInfo) {
    super(con, clientInfo, serverInfo);
  }

  @Override
  public void verifySessionInfo(SessionInfo sessionInfo) {
    // verify the credentials: hands them to the configured AuthenticationProviders
    // (see TrackerPasswordAuthenticationProvider) and sets the user id
    super.verifySessionInfo(sessionInfo);

    LocaleProvider.getInstance().setCurrentLocale(sessionInfo.getLocale());
    getSession().makeCurrent();

    // what's left here belongs to the session, not to the verification of the credentials
    if (!sessionInfo.isCloned()) {
      // user must be logged in only once (per main session)
      SessionInfo otherInfo = isUserLoggedIn(sessionInfo);
      if (otherInfo != null) {
        throw new AlreadyLoggedInException(getSession(), otherInfo);
      }
      if (!getSession().isRemote()) {
        DomainContext context = Pdo.createDomainContext(getSession());
        User user = Application.getInstance().getUser(context, sessionInfo.getUserId());
        String message=MessageFormat.format(ServerBundle.getString("user {0} logged in from {1} with {2}, session {3}"),
        user,sessionInfo.getHostInfo(),sessionInfo.getApplicationName(),getSessionNumber());
        Message.log(MessageType.LOGIN,user,message,user);
      }
      loggedIn = true;
    }
  }

  @Override
  protected void closeDb(boolean cleanup) {
    Db session = getSession();
    if (session != null && !session.isRemote()) {
      try {
        TrackerSessionInfo sessionInfo = (TrackerSessionInfo) getClientSessionInfo();
        if (!sessionInfo.isCloned() &&     // if user's main session
            !ModificationTracker.getInstance().isTerminationRequested()) {    // and no emergency shutdown requested
          DomainContext context = Pdo.createDomainContext(session);
          User user = Application.getInstance().getUser(context, sessionInfo.getUserId());
          LocaleProvider.getInstance().setCurrentLocale(sessionInfo.getLocale());
          session.makeCurrent();
          String message = null;
          if (user == null) {
            // don't log the username, since it could be the password (mixed up by the user accidentally)
            message = MessageFormat.format(ServerBundle.getString("bad login attempt with {0} from {1}"),
                                           sessionInfo.getApplicationName(), sessionInfo.getHostInfo());
          }
          else if (loggedIn) {
            message = MessageFormat.format(ServerBundle.getString("user {0} logged out from {1} with {2}, session {3}"),
                                           user, sessionInfo.getHostInfo(), sessionInfo.getApplicationName(), getSessionNumber());
          }
          if (message != null) {
            if (cleanup) {
              message = MessageFormat.format(ServerBundle.getString("crashed {0}"), message);
            }
            Message.log(MessageType.LOGOUT, user, message, user);
          }
        }
      }
      catch (RuntimeException rex) {
        LOGGER.warning("could not create logout message for " + this, rex);
      }
    }
    super.closeDb(cleanup);
  }

}
