/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server.trip;

import com.example.tracker.common.Version;
import com.example.tracker.persist.trip.TrackerConnection;

import org.tentackle.dbms.trip.RemoteDbConnectionImpl;
import org.tentackle.dbms.trip.RemoteDbSession;
import org.tentackle.dbms.trip.TripServer;
import org.tentackle.session.SessionInfo;
import org.tentackle.session.VersionIncompatibleException;
import org.tentackle.trip.Transport;

/**
 * Application-specific remote connection.
 */
public class TrackerRemoteDbConnectionImpl extends RemoteDbConnectionImpl implements TrackerConnection {

  /**
   * Creates a connection.
   *
   * @param server the server
   * @param transport the transport
   */
  public TrackerRemoteDbConnectionImpl(TripServer server, Transport transport) {
    super(server, transport);
  }

  @Override
  public RemoteDbSession createSession(SessionInfo clientInfo) {
    return new TrackerRemoteDbSessionImpl(this, clientInfo, getServer().getSessionInfo());
  }

  @Override
  public void checkClientVersion(String clientVersion) {
    if (!Version.RELEASE.equals(clientVersion)) {
      throw new VersionIncompatibleException("incompatible client", clientVersion, Version.RELEASE);
    }
  }

}
