/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server.trip;

import com.example.tracker.common.Version;

import org.tentackle.update.AbstractUpdateServiceImpl;


/**
 * Server side update service implementation.
 */
public class UpdateServiceImpl extends AbstractUpdateServiceImpl {

  /**
   * Creates an update service object.
   *
   * @param updateURL the http url where to download the updates from
   */
  public UpdateServiceImpl(String updateURL) {
    super(updateURL);
  }

  @Override
  public String getArtifactName() {
    return "tracker-jlink-client";
  }

  @Override
  public String getVersion() {
    return Version.RELEASE;
  }

}
