/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.trip;

import com.example.tracker.pdo.TrackerRemoteSession;

import org.tentackle.dbms.trip.RemoteDbSession;
import org.tentackle.persist.PdoRemoteSessionAdapter;

/**
 * Application-specific remote session adapter.
 */
public class TrackerRemoteSessionAdapter extends PdoRemoteSessionAdapter implements TrackerRemoteSession {

  public TrackerRemoteSessionAdapter(RemoteDbSession rs) {
    super(rs);
  }

  @Override
  public TrackerRemoteDbSession getRemoteDbSession() {
    return (TrackerRemoteDbSession) super.getRemoteDbSession();
  }

}
