/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.trip;

import org.tentackle.dbms.trip.RemoteDbConnection;

/**
 * Interface for the appliction specific connection.
 */
public interface TrackerConnection extends RemoteDbConnection {

}
