/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.persist.trip;

import org.tentackle.dbms.trip.RemoteDbSession;

/**
 * Interface for the remote session.
 */
public interface TrackerRemoteDbSession extends RemoteDbSession {

}
