/*
 * Tracker generated by tentackle-project-archetype.
 */

package com.example.tracker.server.rmi;

import com.example.tracker.common.Version;

import org.tentackle.update.AbstractUpdateServiceImpl;

import java.io.Serial;
import java.rmi.RemoteException;


/**
 * Server side update service implementation.
 */
public class UpdateServiceImpl extends AbstractUpdateServiceImpl {

  @Serial
  private static final long serialVersionUID = 1L;

  /**
   * Creates an update service object.
   *
   * @param port the tcp-port, 0 = system default
   * @param updateURL the http url where to download the updates from
   * @throws RemoteException if failed to export object
   */
  public UpdateServiceImpl(int port, String updateURL) throws RemoteException {
    super(port, updateURL);
  }

  @Override
  public String getArtifactName() {
    return "tracker-jlink-client";
  }

  @Override
  public String getVersion() {
    return Version.RELEASE;
  }

}
